# Generated by Django 2.2.6 on 2019-10-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raw_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Charge_Station_Name', models.CharField(max_length=800)),
                ('Session_Initiated_By', models.CharField(max_length=800)),
                ('Start_Time', models.CharField(max_length=800)),
                ('End_Time', models.CharField(max_length=800)),
                ('Duration', models.CharField(max_length=800)),
                ('Energy', models.CharField(max_length=800)),
                ('Session_Amount', models.CharField(max_length=800)),
                ('Session_Id', models.CharField(max_length=800)),
                ('Port_Type', models.CharField(max_length=800)),
                ('Payment_Mode', models.CharField(max_length=800)),
            ],
        ),
    ]
