# Generated by Django 2.2.6 on 2019-11-03 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0002_processed_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Processed_data',
        ),
    ]
