# Generated by Django 2.2.6 on 2019-11-10 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0002_procc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raw_data',
            name='Payment_Mode',
        ),
    ]
